### PR TITLE
add ilk to FileEvent

### PR DESCRIPTION
**Pull request by levity**

### CODE REVIEW

**Comment by rmulhol** [comment]
perhaps it's worth considering having two separate structs? thinking we could have one tailored for `ilk` and another for `address`

**Comment by levity** [comment]
what else would go in the `address` struct besides the string representation? i'm open to the idea, was just trying to follow the convention already being used elsewhere in the file

**Comment by rmulhol** [comment]
I was more thinking that perhaps we'd want separate structs depending on whether or not an ilk was (could ever be) populated. So like a `FileIlkEvent` that matches the spec you proposed, and a `ContractFileEvent` that omitted the `ilkID` and `ilk` fields.

That said I suppose that could make it difficult to define the type for fields where `[FileEvent]` is expected to return both types, and I have a working version using this template. So I'm more than happy to go with this and then iterate later as necessary.

**Comment by levity** [comment]
Oh, I get what you mean now. Yeah, let's stick with a single FileEvent. You could use an [interface](https://graphql.org/learn/schema/#interfaces) if you wanted to differentiate, but I don't see any harm in sticking with what we've already got.

**Pull request closed without merging**
